apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: default
spec:
  selector:
    app: rest-api
  type: NodePort
  ports:
    - name: eureka
      port: 7001
      targetPort: 4001
      # If you set the `spec.type` field to `NodePort` and you want a specific port number,
      # you can specify a value in the `spec.ports[*].nodePort` field.
      nodePort: 30162
