apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: default
spec:
  selector:
    app: rest-api
  type: NodePort
  ports:
    - name: eureka
      port: 7001
      targetPort: 4001
      nodePort: 30162
