#headless service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    app: mysql
  type: ClusterIP
  ClusertIP: None
  ports:
  - name: mysql
    protocol: TCP
    port: 3306