# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngrs-service
  namespace: default
spec:
  rules:
    - host: locslhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rest-api-service
                port:
                  number: 4001
