apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: default
  labels:
    app: rest-api
spec:
  selector:
    matchLabels:
      app: rest-api
  replicas: 2
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: amitchavda00/rest-api:1.0
        
