apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: default
  labels:
    app: rest-api
spec:
  selector:
    matchLabels:
      app: rest-api
  replicas: 2
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: amitchavda00/rest-api:1.0
          ports:
            - containerPort: 4001
              name: rest-api
---
apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
  namespace: default
spec:
  selector:
    app: rest-api
  ports:
    - name: rest-api-service
      protocol: TCP
      port: 7001
      targetPort: 4001
